# Perform continuous integration tests on updates and pull requests
name: Build test

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            klippy:
              - 'klippy/**'
              - 'test/**'
              - 'scripts/**'
            klipper:
              - 'src/**'
              - 'lib/**'
              - 'test/**'

      - name: Test Klippy Only
        if: steps.changes.outputs.klippy == 'true' && steps.changes.outputs.klipper == 'false'
        run: docker run -v $PWD:/klipper dangerklippers/klipper-build:latest "./scripts/ci-build.sh" 2>&1

      - name: Test Klipper Full
        if: steps.changes.outputs.klippy == 'true' && steps.changes.outputs.klipper == 'true'
        run: docker run -v $PWD:/klipper dangerklippers/klipper-build:latest "./scripts/ci-build.sh" compile 2>&1
